Repository momocus/sakazuki, pull requests merged in 2021-01, with the labels that each got.

#129 Contributionを追加した
  README.md
  cli-scripts/run-all-checks.sh
Labels: documentation

#130 MarkdownとStylesheetのLintを追加した
  .github/workflows/gem.yml
  .github/workflows/node.yml
  .stylelintrc.json
  README.md
  app/javascript/src/stylesheet/application.scss
  cli-scripts/run-all-checks.sh
  package.json
  yarn.lock
Labels: dependencies, documentation

#135 全文検索もどきを実装した
  Gemfile
  Gemfile.lock
  app/controllers/sakes_controller.rb
  app/helpers/sakes_helper.rb
  app/models/search/base.rb
  app/models/search/sake.rb
  app/views/sakes/index.html.erb
  config/locales/models/ja.yml
Labels: design, enhancement, ruby

#137 Email認証
  README.md
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  db/migrate/20210126072328_add_column_to_users.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement, ruby

#138 ソート機能をRansackで実現した
  app/controllers/sakes_controller.rb
  app/javascript/src/stylesheet/application.scss
  app/views/sakes/index.html.erb
Labels: enhancement, ruby

#141 Add docker by iteduki
  .dockerignore
  Dockerfile
  README.md
  config/database.yml
  docker-compose.yml
  entrypoint.sh
Labels: enhancement

#142 Ransackを使って空き瓶表示機能を作成した
  .erb-lint.yml
  app/controllers/sakes_controller.rb
  app/helpers/sakes_helper.rb
  app/models/sake.rb
  app/views/sakes/index.html.erb
  config/initializers/ransack.rb
Labels: enhancement, ruby

#144 開発用Dockerイメージをコンパクトに仕上げた
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: help wanted
